package: ymca
version: 2.0.0
author: alex+ Digitales Marketing, Alexander Walther
supportpage: https://github.com/alexplusde/ymca

page:
    hidden: true

pages:
    yform/yform_docs:
        title: 'Docs Accelerator'
        icon: rex-icon fa-fast-forward
        itemclass: pull-right
        perm: admin
    yform/yform_restful_api:
        title: 'RESTful API Accelerator'
        icon: rex-icon fa-fast-forward
        itemclass: pull-right
        perm: admin
    yform/yform_model_class:
        title: 'Model Class Accelerator'
        icon: rex-icon fa-fast-forward
        itemclass: pull-right
        perm: admin
