package: ymca
version: 2.2.0
author: alex+ Digitales Marketing, Alexander Walther
supportpage: https://github.com/alexplusde/ymca

page:
    hidden: true

pages:
    yform/yform_pdf:
        title: 'PDF'
        icon: rex-icon fa-fast-forward
        itemclass: pull-right
        perm: admin
    yform/yform_docs:
        title: 'Docs'
        icon: rex-icon fa-fast-forward
        itemclass: pull-right
        perm: admin
    yform/yform_restful_api:
        title: 'RESTful-API'
        icon: rex-icon fa-fast-forward
        itemclass: pull-right
        perm: admin
    yform/yform_model_class:
        title: 'YOrm-Model-Class'
        icon: rex-icon fa-fast-forward
        itemclass: pull-right
        perm: admin
