package: ymca
version: 0.0.3
author: alex+ Digitales Marketing, Alexander Walther
supportpage: https://github.com/alexplusde/ymca

page:
    hidden: true

pages:
    yform/yform_model_class:
        title: 'Model Class Generator'
        icon: rex-icon fa-fast-forward
        itemclass: pull-right
        perm: project[]
