package: ymca
version: 2.2.0
author: alex+ Digitales Marketing, Alexander Walther
supportpage: https://github.com/alexplusde/ymca

page:
    hidden: true
    title: 'YMCA'

pages:
    yform/ymca:
        title: 'YMCA'
        icon: rex-icon fa-fast-forward
        itemClass: pull-right
        perm: admin
    yform/ymca/yorm:
        title: 'YOrm'
        icon: rex-icon fa-fast-forward
        perm: admin
    yform/ymca/restful_api:
        title: 'RESTful-API'
        icon: rex-icon fa-fast-forward
        perm: admin
    yform/ymca/docs:
        title: 'Docs'
        icon: rex-icon fa-fast-forward
        perm: admin
    yform/ymca/dotlang:
        title: '.lang'
        icon: rex-icon fa-fast-forward
        perm: admin
    yform/ymca/pdf:
        title: 'PDF'
        icon: rex-icon fa-fast-forward
        perm: admin
