package: ymca
version: 1.0.5
author: alex+ Digitales Marketing, Alexander Walther
supportpage: https://github.com/alexplusde/ymca

page:
    hidden: true

pages:
    yform/yform_model_class:
        title: 'Model Class Accelerator'
        icon: rex-icon fa-fast-forward
        itemclass: pull-right
        perm: admin
